# Generated by Django 3.2.7 on 2021-09-18 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import employee.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('deptName', models.CharField(max_length=25, null=True, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empID', models.CharField(default=employee.utils.create_new_ref_number, max_length=8, primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('fName', models.CharField(blank=True, max_length=25, null=True, verbose_name='first name')),
                ('lName', models.CharField(blank=True, max_length=25, null=True, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hireDate', models.DateField(auto_now_add=True, null=True, verbose_name='Date joined')),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='username')),
                ('deptID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.department', verbose_name='department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employee.employee')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='This employee management system is great!', max_length=255, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(null=True, verbose_name='End Date')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=25, verbose_name='Status')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
