# Generated by Django 3.2.7 on 2021-09-07 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210907_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empmanager',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='empmanager',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='title',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='deptID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='DeptEmployee',
        ),
        migrations.DeleteModel(
            name='EmpManager',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
