# Generated by Django 3.2.7 on 2021-09-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20210908_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='empID',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='Employee ID'),
        ),
    ]
