# Generated by Django 3.2.7 on 2021-09-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20210909_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empID',
            field=models.CharField(default='30812073', max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='Employee ID'),
        ),
    ]
