# Generated by Django 3.2.7 on 2021-09-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employee_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empID',
            field=models.CharField(default='15503929', max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='Employee ID'),
        ),
    ]
