# Generated by Django 3.2.7 on 2021-09-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='username'),
        ),
    ]
