# Generated by Django 3.2.7 on 2021-09-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
