# Generated by Django 3.2.7 on 2021-09-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_leave_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=25, verbose_name='Status'),
        ),
    ]
