# Generated by Django 3.2.7 on 2021-09-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_request',
            name='end_date',
            field=models.DateField(null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='leave_request',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Start Date'),
        ),
    ]
