# Generated by Django 3.2.7 on 2021-09-14 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_auto_20210913_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
