# Generated by Django 3.2.7 on 2021-09-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_auto_20210914_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default='This employee management system is great!', max_length=255, null=True),
        ),
    ]
